baseURL = 'https://bachirlog.dev/'
languageCode = 'en-us'
title = 'BachirLOG'
theme = "anubis2"


[pagination]
pagerSize = 5

[params.author]
name = "BachirLOG"

[params]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = false

colorTheme = "auto"
colorThemeSwitcher = true
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true
enableEmoji = true
# Graphcomment support
graphcommentId = ""

customCSS = ["custom-css/custom1.scss", "custom-css/custom2.css"]

social = [
    { id = "github", url = "https://github.com/bmoussat/" },
    { id = "linkedin", url = " https://www.linkedin.com/in/bachir-moussa-tari-bako-99668354/" },
    { id = "email", url = "bachirtarimoussa|ATATgmail.com" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
tabWidth           = 4
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/